#!/usr/bin/env node
// tsadt: compile .tsa files (TypeScript + data/match) to plain .ts files.

import fs from "node:fs";
import path from "node:path";
import { collectDataDecls, Diagnostic, formatDiagnostic, transpile } from "./transpiler.js";
import { Registry } from "./registry.js";
import { checkAndEmit, emitFast, Generated, loadCompilerOptions, WriteFile, writeToDisk } from "./emit.js";

const USAGE = `Usage: tsadt [options] <file.tsa | dir>...

Compiles TypeScript with algebraic data types and pattern matching to plain
TypeScript. Each input.tsa becomes input.ts. Directories are searched
recursively for .tsa files. All inputs share one constructor registry, so a
match in one file can use constructors declared in another.

Output modes:
  (default)            Write .ts files
      --check          Also type check the generated code with tsc
      --js             Write .js files instead (types stripped, no checking)
      --js --check     Type check, then write .js files only if there are
                       no errors

Options:
  -o, --outDir <dir>   Write output under <dir>, mirroring the input layout
                       (default: next to each input)
      --stdout         Print the output instead of writing files
      --tsconfig <f>   Compiler options for --js and --check (default:
                       strict, ES2022, NodeNext). outDir/rootDir are ignored;
                       use -o.
      --tag <name>     Discriminant field name (default: tag)
  -h, --help           Show this help

--js compiles only the .tsa files given. Plain .ts files they import are
type checked by --check but compiled by your usual build.`;

interface Input {
  file: string;
  base: string;
}

function findInputs(arg: string): Input[] {
  const stat = fs.statSync(arg, { throwIfNoEntry: false });
  if (!stat) throw new Error(`No such file or directory: ${arg}`);
  if (stat.isFile()) return [{ file: arg, base: path.dirname(arg) }];
  const out: Input[] = [];
  const walk = (dir: string) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (e.name === "node_modules" || e.name.startsWith(".")) continue;
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith(".tsa")) out.push({ file: p, base: arg });
    }
  };
  walk(arg);
  return out;
}

function main(argv: string[]): number {
  const inputs: Input[] = [];
  let outDir: string | null = null;
  let toStdout = false;
  let tagField: string | undefined;
  let js = false;
  let check = false;
  let tsconfig: string | null = null;

  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "-h" || a === "--help") {
      console.log(USAGE);
      return 0;
    } else if (a === "-o" || a === "--outDir") outDir = argv[++i];
    else if (a === "--stdout") toStdout = true;
    else if (a === "--tag") tagField = argv[++i];
    else if (a === "--js") js = true;
    else if (a === "--check") check = true;
    else if (a === "--tsconfig") tsconfig = argv[++i];
    else if (a.startsWith("-")) {
      console.error(`Unknown option ${a}\n\n${USAGE}`);
      return 2;
    } else inputs.push(...findInputs(a));
  }
  if (inputs.length === 0) {
    console.error(USAGE);
    return 2;
  }

  // Pass 1: register every data declaration. Pass 2: translate each file.
  const opts = { tagField };
  const reg = new Registry();
  const sources = inputs.map((inp) => ({ ...inp, src: fs.readFileSync(inp.file, "utf8") }));
  const diags: Diagnostic[] = [];
  // A file whose declarations failed to parse is not translated: that would
  // report the same errors a second time.
  const broken = new Set<string>();
  for (const s of sources) {
    const ds = collectDataDecls(s.src, s.file, reg, opts);
    diags.push(...ds);
    if (ds.some((d) => d.severity === "error")) broken.add(s.file);
  }

  const generated: Generated[] = [];
  for (const s of sources) {
    if (broken.has(s.file)) continue;
    const res = transpile(s.src, s.file, reg, opts);
    diags.push(...res.diagnostics);
    if (res.diagnostics.some((d) => d.severity === "error")) continue;
    const rel = path.relative(s.base, s.file).replace(/\.tsa$/, "");
    const header = `// Generated by tsadt from ${path.basename(s.file)}. Do not edit.\n`;
    generated.push({
      tsaPath: s.file,
      code: header + res.code,
      outBase: outDir ? path.join(outDir, rel) : path.join(s.base, rel),
      sourcePosition: (offset) => (offset < header.length ? null : res.sourcePosition(offset - header.length)),
    });
  }
  for (const d of diags) console.error(formatDiagnostic(d));
  let errors = diags.filter((d) => d.severity === "error").length;

  const write: WriteFile = toStdout ? (_dest, text) => process.stdout.write(text) : writeToDisk;
  let written = 0;

  if (!js) {
    for (const g of generated) {
      write(g.outBase + ".ts", g.code);
      written++;
    }
  }

  // Type check / emit JavaScript only when the translation itself succeeded,
  // since a missing file would show up as confusing import errors.
  if ((js || check) && errors === 0) {
    const compilerOptions = loadCompilerOptions(tsconfig);
    const res = check ? checkAndEmit(generated, compilerOptions, js, write) : emitFast(generated, compilerOptions, write);
    for (const d of res.diagnostics) console.error(d);
    errors += res.errors;
    if (js) written += res.written.length;
  } else if (js && errors > 0) {
    console.error("tsadt: no JavaScript written because of the errors above");
  }

  if (!toStdout) console.error(`tsadt: wrote ${written} file(s), ${errors} error(s)`);
  return errors > 0 ? 1 : 0;
}

try {
  process.exitCode = main(process.argv.slice(2));
} catch (e) {
  console.error(`tsadt: ${(e as Error).message}`);
  process.exitCode = 2;
}
