// Compiling transpiled output to JavaScript with the TypeScript compiler API.
//
// Two modes:
// - emitFast: strips types file by file (ts.transpileModule). No checking.
// - checkAndEmit: builds a real ts.Program in which each foo.tsa appears as
//   an in-memory foo.ts next to it, type checks everything, and emits
//   JavaScript only when there are no errors. Imports between .tsa files and
//   plain .ts files in your project resolve as usual.

import fs from "node:fs";
import path from "node:path";
import ts from "typescript";

export interface Generated {
  /** The .tsa source path. */
  tsaPath: string;
  /** Generated TypeScript (what --stdout prints for a .tsa file). */
  code: string;
  /** Output path without extension, e.g. out/list for out/list.js. */
  outBase: string;
  /** Maps an offset in `code` to a line and column in the .tsa file. */
  sourcePosition?(offset: number): { line: number; col: number } | null;
}

export const DEFAULT_COMPILER_OPTIONS: ts.CompilerOptions = {
  target: ts.ScriptTarget.ES2022,
  module: ts.ModuleKind.NodeNext,
  moduleResolution: ts.ModuleResolutionKind.NodeNext,
  strict: true,
  skipLibCheck: true,
};

export function loadCompilerOptions(tsconfig: string | null): ts.CompilerOptions {
  if (!tsconfig) return { ...DEFAULT_COMPILER_OPTIONS };
  const read = ts.readConfigFile(tsconfig, ts.sys.readFile);
  if (read.error) throw new Error(ts.flattenDiagnosticMessageText(read.error.messageText, "\n"));
  const parsed = ts.parseJsonConfigFileContent(read.config, ts.sys, path.dirname(path.resolve(tsconfig)));
  // TS18003 "No inputs were found": expected when the project has only .tsa
  // files. tsadt uses just the compiler options, not the file list.
  const errors = parsed.errors.filter((e) => e.code !== 18003);
  if (errors.length) {
    throw new Error(errors.map((e) => ts.flattenDiagnosticMessageText(e.messageText, "\n")).join("\n"));
  }
  return parsed.options;
}

/** Keeps the "Generated by" header, which TypeScript drops along with erased type declarations. */
function withBanner(gen: Generated, dest: string, text: string): string {
  if (!/\.[cm]?js$/.test(dest)) return text;
  const banner = `// Generated by tsadt from ${path.basename(gen.tsaPath)}. Do not edit.\n`;
  return text.startsWith(banner) ? text : banner + text;
}

/** Where a compiler output file goes: the .tsa's output base plus the emitted extension. */
function destFor(outBase: string, emitted: string): string {
  for (const ext of [".d.ts", ".js.map", ".d.ts.map", ".mjs", ".cjs", ".js"]) {
    if (emitted.endsWith(ext)) return outBase + ext;
  }
  return outBase + path.extname(emitted);
}

/**
 * With module Node16/NodeNext, whether a file is ESM or CommonJS depends on
 * the nearest package.json. transpileModule cannot look that up, so do it here.
 */
function moduleKindFor(file: string, options: ts.CompilerOptions): ts.ModuleKind | undefined {
  const m = options.module;
  if (m !== ts.ModuleKind.Node16 && m !== ts.ModuleKind.NodeNext) return m;
  for (let dir = path.dirname(path.resolve(file)); ; dir = path.dirname(dir)) {
    const pj = path.join(dir, "package.json");
    if (fs.existsSync(pj)) {
      try {
        return JSON.parse(fs.readFileSync(pj, "utf8")).type === "module" ? ts.ModuleKind.ESNext : ts.ModuleKind.CommonJS;
      } catch {
        return ts.ModuleKind.CommonJS;
      }
    }
    if (path.dirname(dir) === dir) return ts.ModuleKind.CommonJS;
  }
}

export interface EmitResult {
  /** Formatted diagnostics, one per entry. */
  diagnostics: string[];
  errors: number;
  /** Files written, in order. */
  written: string[];
}

export type WriteFile = (dest: string, text: string) => void;

export const writeToDisk: WriteFile = (dest, text) => {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, text);
};

/** Strips types from each file independently. Reports syntax errors only. */
export function emitFast(files: Generated[], options: ts.CompilerOptions, write: WriteFile = writeToDisk): EmitResult {
  const result: EmitResult = { diagnostics: [], errors: 0, written: [] };
  for (const f of files) {
    const fileName = f.tsaPath.replace(/\.tsa$/, ".ts");
    const compilerOptions: ts.CompilerOptions = {
      ...options,
      module: moduleKindFor(f.tsaPath, options),
      declaration: false,
      sourceMap: false,
      noEmit: false,
    };
    delete compilerOptions.moduleResolution; // irrelevant when stripping types
    const out = ts.transpileModule(f.code, { fileName, reportDiagnostics: true, compilerOptions });
    const diags = out.diagnostics ?? [];
    result.diagnostics.push(...diags.map((d) => formatDiagnostic(d, new Map())));
    const errs = diags.filter((d) => d.category === ts.DiagnosticCategory.Error).length;
    result.errors += errs;
    if (errs > 0) continue;
    const dest = f.outBase + ".js";
    write(dest, withBanner(f, dest, out.outputText));
    result.written.push(dest);
  }
  return result;
}

/**
 * Type checks the generated files together with whatever they import, then
 * emits JavaScript for the generated files. Emits nothing if there are errors.
 * With `emit: false` it only checks.
 */
export function checkAndEmit(
  files: Generated[],
  options: ts.CompilerOptions,
  emit: boolean,
  write: WriteFile = writeToDisk,
): EmitResult {
  const opts: ts.CompilerOptions = { ...options, noEmit: !emit, noEmitOnError: false };
  delete opts.outDir;
  delete opts.outFile;
  delete opts.rootDir;

  // Each foo.tsa is presented to the compiler as an in-memory foo.ts.
  const virtual = new Map<string, Generated>();
  for (const f of files) virtual.set(path.resolve(f.tsaPath.replace(/\.tsa$/, ".ts")), f);

  const host = ts.createCompilerHost(opts);
  const { fileExists, readFile, getSourceFile } = host;
  host.fileExists = (f) => virtual.has(path.resolve(f)) || fileExists.call(host, f);
  host.readFile = (f) => virtual.get(path.resolve(f))?.code ?? readFile.call(host, f);
  host.getSourceFile = (f, lang, onError, create) => {
    const v = virtual.get(path.resolve(f));
    return v ? ts.createSourceFile(f, v.code, lang, true) : getSourceFile.call(host, f, lang, onError, create);
  };

  const program = ts.createProgram([...virtual.keys()], opts, host);
  const diags = [...ts.getPreEmitDiagnostics(program)];
  const result: EmitResult = {
    // A field type is copied into both the union and its constructor, so one
    // mistake there yields two identical messages once mapped back to .tsa.
    diagnostics: [...new Set(diags.map((d) => formatDiagnostic(d, virtual)))],
    errors: diags.filter((d) => d.category === ts.DiagnosticCategory.Error).length,
    written: [],
  };
  if (!emit || result.errors > 0) return result;

  for (const [tsPath, gen] of virtual) {
    const sf = program.getSourceFile(tsPath);
    if (!sf) continue;
    const res = program.emit(sf, (emitted, text) => {
      const dest = destFor(gen.outBase, emitted);
      write(dest, withBanner(gen, dest, text));
      result.written.push(dest);
    });
    result.diagnostics.push(...res.diagnostics.map((d) => formatDiagnostic(d, virtual)));
  }
  return result;
}

function formatDiagnostic(d: ts.Diagnostic, virtual: Map<string, Generated>): string {
  const msg = ts.flattenDiagnosticMessageText(d.messageText, "\n");
  const sev = ts.DiagnosticCategory[d.category].toLowerCase();
  let text = `${where(d.file, d.start, virtual)}${sev} TS${d.code}: ${msg}`;
  for (const r of d.relatedInformation ?? []) {
    text += `\n  ${where(r.file, r.start, virtual)}${ts.flattenDiagnosticMessageText(r.messageText, "\n")}`;
  }
  return text;
}

/** "file:line:col: ", pointing into the .tsa file when the code was generated. */
function where(file: ts.SourceFile | undefined, start: number | undefined, virtual: Map<string, Generated>): string {
  if (!file || start === undefined) return "";
  const gen = virtual.get(path.resolve(file.fileName));
  const mapped = gen?.sourcePosition?.(start);
  if (gen && mapped) return `${path.relative(process.cwd(), gen.tsaPath)}:${mapped.line}:${mapped.col}: `;
  const { line, character } = file.getLineAndCharacterOfPosition(start);
  const name = gen ? gen.tsaPath.replace(/\.tsa$/, ".ts") + " (generated)" : file.fileName;
  return `${path.relative(process.cwd(), name)}:${line + 1}:${character + 1}: `;
}
